language: python
sudo: false
branches:
only:
  - master
python:
  - "3.5"
  - "3.6"

# to add testing, replace {PACKAGE NAME} with your package's name, and {AUTHOR_EMAILS} with a
# YAML list of author emails, like:
# - robert@gmail.com
# - betsy@gmail.com
# - frank@gmail.com

env:
  - PYSAL_PLUS=false MPLBACKEND='pdf'
  - PYSAL_PLUS=true MPLBACKEND='pdf'

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda config --append channels conda-forge
  - conda create -y -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env

install:
  - conda install --yes pip
  - conda install --yes --file requirements.txt;
  - conda install -c conda-forge geopandas
  - pip install -r requirements_dev.txt

script:
  - python setup.py sdist >/dev/null
  - python setup.py install
  - nosetests --with-coverage --cover-package={PACKAGE_NAME} {PACKAGE_NAME}

notifications:
    email:
        recipients:
            {AUTHOR_EMAILS}
        on_change: always
        on_failure: always

after_success:
  - coveralls
